# Real-world implementation of the scholarAI workflow (Part 3)
# This file checks that the scholar function actually runs
#
# This file depends on the output from test-full-implementation-part2.R

out_dir <- file.path(
  testthat::test_path(),
  "test_data",
  "real_world_implementation"
)

# Step 7: Generate scholar functions
message("STEP 7: Generating scholar functions")

# Generate scholar functions and test in the same block
test_that("Scholar functions can be generated", {
  # Create a custom output file path in the test directory
  custom_output_file <- file.path(out_dir, "custom.R")

  # Generate scholar functions using the configuration
  result <- scholarAI:::generate_scholar_functions(
    authors = "Tobias%20Peter",
    output_dir = out_dir, # Specify output directory explicitly
    custom_file = custom_output_file, # Specify custom file path explicitly
    progress = FALSE
  )

  # Verify the custom file was created in the expected location
  expect_true(
    file.exists(custom_output_file),
    "Custom file was not created in the expected location"
  )

  # Verify the custom file contains the expected content
  custom_content <- readLines(custom_output_file)
  expect_true(
    any(grepl("askTobias", custom_content)),
    "Custom file does not contain the expected function"
  )

  # Print function generation info
  message(
    "Scholar functions generated: ",
    paste(result$scholar_functions, collapse = ", ")
  )
  message("Custom file created at: ", result$custom_file)

  # Test assertions
  expect_true(file.exists(result$custom_file), "Custom file not created")
  expect_true(
    length(result$scholar_functions) > 0,
    "No scholar functions generated"
  )

  # Check that the function is available in the global environment
  # Note: In a test environment, functions aren't assigned to .GlobalEnv
  # So we'll just check the file content
  custom_content <- readLines(result$custom_file)
  expect_true(
    any(grepl("askTobias", custom_content)),
    "Scholar function not found in custom file"
  )
})


# Step 8: Test running the scholar functions
message("STEP 8: Testing scholar functions")

test_that("Scholar functions can be generated and loaded", {
  # Load the custom file with scholar functions
  custom_file <- file.path(out_dir, "custom.R")
  expect_true(file.exists(custom_file), "Custom file not found")

  # Fix the custom file before sourcing it
  # The issue is with how the timestamp is formatted in the file
  custom_content <- readLines(custom_file)

  # Find the lines with the timestamp issue
  timestamp_comment_line <- grep(
    "# Generated by the scholarAI package on",
    custom_content
  )
  if (
    length(timestamp_comment_line) > 0 &&
      timestamp_comment_line + 1 <= length(custom_content)
  ) {
    # Combine the comment line with the timestamp line
    custom_content[timestamp_comment_line] <- paste0(
      custom_content[timestamp_comment_line],
      " ",
      custom_content[timestamp_comment_line + 1]
    )
    # Remove the timestamp line
    custom_content <- custom_content[-(timestamp_comment_line + 1)]
    # Write the fixed content back to the file
    writeLines(custom_content, custom_file)
  }

  # Source the fixed custom file to load the functions
  source(custom_file)

  # Check if askTobias function is available
  expect_true(exists("askTobias"), "askTobias function not found")

  # Verify the function has the expected structure
  expect_true(is.function(askTobias), "askTobias is not a function")

  # Check function arguments
  ask_scholar_args <- formals(ask_scholar)
  fn_args <- formals(askTobias)
  required_args <- c("query", "limit", "temperature", "db_path")
  for (arg in names(ask_scholar_args)) {
    expect_true(
      arg %in% names(fn_args),
      sprintf("askTobias missing '%s' argument", arg)
    )
  }
})

test_that("Scholar functions can be run with real API calls", {
  custom_file <- file.path(out_dir, "custom.R")
  source(custom_file)

  # Run the askTobias function with a simple query
  test_query <- "What are your thoughts on housing policy in 150 words?"
  message("Testing askTobias with query: '", test_query, "'")

  # Use tryCatch to handle potential errors gracefully
  response <- askTobias(
    test_query,
    limit = 1,
    api_args = list(temperature = 0.7),
    progress = TRUE
  )

  # Check if we got a response
  expect_false(is.null(response), "No response from askTobias")
  expect_true(is.character(response), "Response is not a character string")
  expect_true(nchar(response) > 0, "Response is empty")

  # Print a summary of the response
  if (!is.null(response)) {
    response_preview <- substr(response, 1, min(100, nchar(response)))
    message("Response preview: '", response_preview, "...'")
  }
})


# Print summary of the implementation
message("Real-world implementation part 2 completed successfully")
message("Output directory: ", out_dir)
message("Scholar functions generated and tested successfully")
